version: 0.2

phases:

  pre_build:

    commands:

      - $(aws ecr get-login)

      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"

  build:

    commands:

      - docker build --tag "548284823708.dkr.ecr.us-east-2.amazonaws.com/store:${TAG}" .

  post_build:

    commands:

      - docker push "548284823708.dkr.ecr.us-east-2.amazonaws.com/store:${TAG}"

      - printf '{"store":"%s"}' $TAG > store.json

artifacts:

  files: store.json
