version: 0.2

phases:

  pre_build:

    commands:

      - $(aws ecr get-login)

      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"

  build:

    commands:

      - docker build --tag "877278458853.dkr.ecr.ap-northeast-1.amazonaws.com/tokai-cicd-ecr:${TAG}" .

  post_build:

    commands:

      - docker push "877278458853.dkr.ecr.ap-northeast-1.amazonaws.com/tokai-cicd-ecr:${TAG}"

      - printf '{"tag":"%s"}' $TAG > build.json

artifacts:

  files: build.json
