version: 0.2

phases:

  pre_build:

    commands:
      - aws --version

      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)

      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - REPO_URL=548284823708.dkr.ecr.us-east-2.amazonaws.com/store

  build:

    commands:

      - docker build --tag $REPO_URL:$TAG .

  post_build:

    commands:

      - docker push $REPO_URL:$TAG

      - printf '[{"name":"store","imageUrl":"%s"}]' $REPO_URL:$TAG > store.json

artifacts:

  files: store.json
